### ISSUE TITLE
Missing buttons visible on iPhone 13

### ISSUE THREAD

**Issue by Carl-B-Doro** [rugsmunny/HearingBuds_HearingTest#11]
There is missing buttons on iOS. Tested on iPhone 13.
![image0 (4)](https://github.com/rugsmunny/HearingBuds_HearingTest/assets/142970511/195c7707-d697-4e97-90b9-ec9fb8f0bbc9)

**Comment by rugsmunny** [comment]
That is strange (since you obviously managed to get to this page by clicking "Start test ->" and "<- Back" button being visible on the page). Have you any idea what the issue could possibly be? (I ran some tests on an iphone simulator and the dropdown wouldn't open when I clicked/touched them). 
I will look further into it and hopefully solve it soon.

**Comment by Carl-B-Doro** [comment]
This bug was found on https://rugsmunny.github.io/Doro_HearingTest/. I was not given the latest version. After now doing a retest with the newest version this seems to be fixed. Both buttons are visible. Dropdowns seems to be working as they should. No issues there. This ticket can be closed.
