### ISSUE TITLE
Non-responsive website on smaller display size

### ISSUE THREAD

**Issue by JuliusDoro** [rugsmunny/HearingBuds_HearingTest#13]
Website is not optimized for smaller display size. 
**Screenshot 1:** Page looks compressed
**Screenshot 2:** Page looks like it is in desktop mode with all the whitespace to the right

**Device:** iPhone 5s - iOS 12.5.7
**Browser:** Safari
![IMG_0004](https://github.com/rugsmunny/HearingBuds_HearingTest/assets/173239441/f50081a4-be66-4771-9bbe-8ee7f2dff496)

![IMG_0005](https://github.com/rugsmunny/HearingBuds_HearingTest/assets/173239441/d696d8a3-912d-4058-a665-d87fc43cd948)

**Comment by rugsmunny** [comment]
Hi Julius,
The specs said that the module should be responsive all the way down to
360px. While trying it out it still looks good below 320px.

I am not sure but it seems that the issue at hand is backward
compatibility.
Many reports shows that iOS 12.5.7 is outdated for browsing web content.
Some suggest that third party browsers such as Opera might overcome these
issues. But as the moment pages like Youtube and Netflix do not support iOS
12.5.7.
On top of that; Apple came out with a report june 12 2024 that indicates
that iOS 12.5s prior security issues were fixed with the 12.5.7 update.
After the update reports about the inability to view web content started to
show up. Also iOS 12.5.7 was released january 12 2023 with no further
version updates being announced. So it wouldn't be hard to believe that
there wont be any more iOS 12 updates.

Since I do not have an iPhone 5, would you so kind and check if it looks
the same some browsers other than Safari?

Also I need to check with Sidiq and Markus about how we should handle this
matter.

Sincerely
Karim Sendesni

Den tors 11 juli 2024 09:47JuliusDoro ***@***.***> skrev:

**Comment by MarcusJoh** [comment]
@rugsmunny @JuliusDoro We can close this one as we dont need to support that version if IOS

**Comment by rugsmunny** [comment]
Bästa, då vet jag, tack för snabb återkoppling.

Den tors 11 juli 2024 12:33marcus johansson ***@***.***>
skrev:
