### ISSUE TITLE
Incorrect tone played when switching from left to right ear.

### ISSUE THREAD

**Issue by jensbenthin** [rugsmunny/HearingBuds_HearingTest#7]
I also noted that when switching from left to right ear, the first tone was 8k and not 1k. So I assume that the last tone from left ear was accidentally played again.

The same thing happens if you press "restart the test" then the first tone at the left ear will be 8k (same as the last one was on the previous ear).

**Comment by rugsmunny** [comment]
Solved

**Comment by jensbenthin** [comment]
This issue is also still valid. The behaviour is the same as described in the original comment.

**Comment by rugsmunny** [comment]
I ran tests and I hate to drop the classic "it works on my computer" so could we have a quick online meeting about it?

**Comment by jensbenthin** [comment]
[Doro Hearing Test - Google Chrome 2024-06-10 15-27-55.zip](https://github.com/user-attachments/files/15774098/Doro.Hearing.Test.-.Google.Chrome.2024-06-10.15-27-55.zip)
Please find a video showing the issue attached.

**Comment by rugsmunny** [comment]
I ran some tests again and could not find any bugs. So I looked at the video again since the issues mentioned are clearly there.... and then it hit me. The git issues are being added to this repo, however the repo-page shown in the video is another one I have used for experimenting. I realized it when I noticed that the buttons for choosing with or without headphones are styled in the same way which they are not in this repo. The dropdown in the form is not the same since I went back and changed it to its initial styling. No changes have been made and if it is okey with you I'll await further feedback on the sounds and recommendations and after that I can continue changing the text content.

**Comment by MarcusJoh** [comment]
@rugsmunny Can you provide the correct link then?

**Comment by rugsmunny** [comment]
https://github.com/rugsmunny/HearingBuds_HearingTest/

**Comment by Carl-B-Doro** [comment]
After testing the new patch, I can't reproduce the issue. Seems to be fixed and following requirements.

Tested OK.
