### ISSUE TITLE
Incorrect recommendation when all tones heard at the most quiet

### ISSUE THREAD

**Issue by jensbenthin** [rugsmunny/HearingBuds_HearingTest#8]
According to the spec. if all tones are heard at the most quiet volume, we should recommend the hearing buds as a music and telephone headset.

Right now the text says that we do not recommend at all.

**Comment by rugsmunny** [comment]
Solved

**Comment by jensbenthin** [comment]
This issue is still there. No changes made from what I can see

**Comment by rugsmunny** [comment]
Not quite sure what you mean. I just ran some tests on with-/without headphones with lowest, +lowest, mid-values to highest and  highest value and the result shown in the end are according to the specifics. What am I missing or missunderstanding?

**Comment by Carl-B-Doro** [comment]
This issue seems to be fixed. When choosing 0-15 dB range. Based on 
![image](https://github.com/rugsmunny/HearingBuds_HearingTest/assets/142970511/abec58e5-12b8-4866-9b97-9f4f430beb5a)

"Your hearing sensitivity is within normal range across all frequencies tested.
Based on your online hearing test results, we recommend our HearingBuds for its excellent sound performance during calls and listening to music."

Tested OK
